version: "3"

networks:
  app-network:
    driver: bridge

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: defenseless_development
    networks:
      - app-network

  web:
    build: .
    stdin_open: true
    tty: true
    command: bash -c "bundle exec rails server -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgresql://postgres:secret@db/defenseless_development
    depends_on:
      - db
    networks:
      - app-network
